[content.shortvideo]
n_ideas = 1
languages = ["en"]
text_details = 'Deep, but absolutely random, short text about life'
img_tags = 'Amazing, fantastic, (insert other tags here describing a very specific unrealistic scene)'
extension_method = 'ai'


[ai.speech.elevenlabs]
voice_settings.speed = 1.2

[audio.background]
urls = [
    "https://www.youtube.com/watch?v=57rLUnu23P0",
    "https://www.youtube.com/watch?v=i8km7dWAsQA",
    "https://www.youtube.com/watch?v=NTj5EEM_SOY"
]