[content.shortvideo]
n_ideas = 2
languages = ["en", "pt"]

[audio.background]
urls = [
    "https://www.youtube.com/watch?v=57rLUnu23P0",
    "https://www.youtube.com/watch?v=i8km7dWAsQA",
    "https://www.youtube.com/watch?v=NTj5EEM_SOY"
]